name: CI
on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-python@v5
      with:
        python-version: "3.12"
        architecture: x64
    - run: sudo apt-get update
    - run: sudo apt-get install -y libgirepository-2.0-dev libcairo2-dev
    - uses: actions/checkout@v4
    - run: pip3 install poetry
    - run: ./ci.sh
